// ==UserScript==
// @name         Douban_Monkey - 豆瓣猴
// @namespace    http://tampermonkey.net/
// @version      0.0.4
// @description  douban beautify css injection script, generated by douban-beautify
// @author       Sherlock-V
// @match        https://douban.com
// @match        https://*.douban.com/*
// @icon         https://www.douban.com/favicon.ico
// @grant        GM_addStyle
// @license      MIT
// ==/UserScript==